---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 15672
    name: http
    targetPort: 15672
    nodePort: 31672
  - port: 5672
    name: amqp
    targetPort: 5672
    nodePort: 30672
  selector:
    app: rabbitmq
  type: LoadBalancer
  
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
  - port: 5672
    name: amqp
  selector:
    app: rabbitmq