apiVersion: v1
kind: Service
metadata:
  name: dcs-drnsync
  labels:
    app: dcs-drnsync
spec:
  ports:
  - name: dcs-drnsync
    port: 8818
    targetPort: 8818
  clusterIP: None
  selector:
    app: dcs-drnsync