apiVersion: v1
kind: Service
metadata:
  name: {{ template "library-svc.fullname" . }}
  labels:
    app: {{ template "library-svc.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: dcs-library-svc
    port: {{ .Values.servicePort | default "10810" }}
    targetPort: {{ .Values.servicePort | default "10810" }}
  clusterIP: None
  selector:
    app: {{ template "library-svc.fullname" . }}
