apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dcs-payment-gateway.fullname" . }}
  labels:
    app: {{ template "dcs-payment-gateway.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.properties: |-
    server.port= {{ .Values.servicePort | default "9000" }}
    grpc.server.port = {{ .Values.GrpcPort | default "50500" }}
    stripe.apiKey = {{ .Values.apiKey }}

    spring.datasource.url = jdbc:mysql://{{ .Values.datasource.host }}:{{ .Values.datasource.port | default "3306" }}/{{ .Values.datasource.dbname | default "dcs_payment_gateway_db" }}?{{ .Values.datasource.tinyInt1isBit | default "true" }}&{{ .Values.datasource.autoReconnect | default "true" }}&{{ .Values.datasource.autoReconnectForPools | default "false" }}&{{ .Values.datasource.useUnicode | default "true" }}&{{ .Values.datasource.characterEncoding | default "UTF-8" }}&{{ .Values.datasource.useSSL | default "false" }}
    spring.datasource.username = {{ .Values.datasource.username }}
    spring.datasource.password = {{ .Values.datasource.password }}
    spring.datasource.driver-class-name = com.mysql.jdbc.Driver
    spring.datasource.dbcp2.validation-query = select 1
    spring.jooq.sql-dialect = org.hibernate.dialect.MySQLDialect
    
    #show sql statement
    logging.level.org.hibernate.SQL = {{ .Values.sql.logging | default "Debug" }}
    spring.jpa.generate-ddl = false
