kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zone: ap-southeast-1a
  iopsPerGB: "20"
  encrypted: "false"