name: dcs-director
version: 1.0.0
description: director service for DCS.
keywords:
- dcs
- director
home: https://www.datamesh.com/
maintainers:
- name: Jianjun Xie
  email: jianjunxie@datamesh.com
engine: gotpl
