apiVersion: v1
kind: Service
metadata:
  name: dcs-portal
  labels:
    app: dcs-portal
spec:
  ports:
  - name: dcs-portal
    port: 8822
  clusterIP: None
  selector:
    app: dcs-portal