apiVersion: v1
kind: Service
metadata:
  name: {{ template "dcsmail.fullname" . }}
  labels:
    app: {{ template "dcsmail.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: dcs-mail-svc
    port: {{ .Values.servicePort | default "8094" }}
    targetPort: dcs-mail-svc
  clusterIP: None
  selector:
    app: {{ template "dcsmail.fullname" . }}
