---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: solsson/kafka-manager@sha256:e07b5c50b02c761b3471ebb62ede88afc0625e325fe428316e32fec7f227ff9b
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: zookeeper:2181
        command:
        - ./bin/kafka-manager
        - -Djava.security.auth.login.config=/kafka-manager/conf/kafka_client_jaas.conf
        - -Dhttp.port=80
        volumeMounts:
        - name: manager-conf
          mountPath: /kafka-manager/conf
      volumes:
      - name: manager-conf
        configMap:
          name: manager-config

---
kind: ConfigMap
metadata:
  name: manager-config
  namespace: kafka
apiVersion: v1
data:
  kafka_client_jaas.conf: |-
    KafkaClient {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="admin"
      password="admin-Ikq32pAA38fAfa823y7fXw0IkqfK";
    };
