apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dcsmail.fullname" . }}
  labels:
    app: {{ template "dcsmail.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  service_conf.toml: |-
    title = "DCS gomail service configurations"
    service_port = ":{{ .Values.servicePort  | default "8094" }}"
    log_level = {{ .Values.logLevel | default "Info" | quote }}
    
    send_cloud_user1 = {{ .Values.sendCloud.user | quote }}
    send_cloud_key1  = {{ .Values.sendCloud.key | quote }}
    
    [mysql_config]
        Tag     = "dcs-central-mysql"
        Uname   = {{ .Values.mysql.username | quote}}
        Passwd  = {{ .Values.mysql.password | quote}}
        Host    = {{ .Values.mysql.host | quote}}
        Port    = {{ .Values.mysql.port | default "3306" | quote }}
        Dbname  = {{ .Values.mysql.dbname | default "DCS_MAIL_DB" | quote }}
        Charset = "UTF8"