kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/configmap.md
  ssl-protocols: "TLSv1 TLSv1.1 TLSv1.2"
  use-http2: "false"
  ssl-ciphers: "HIGH:!aNULL:!MD5"
