# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  ports:
  - name: video-service
    port: 10402
  clusterIP: None
  selector:
    app: video-service
