apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "drive-block-svc.fullname" . }}
  labels:
    app: {{ template "drive-block-svc.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  service_conf.toml: |-
    title = "DCS Drive Block Service Configuration. Copyright @DataMesh, 2017."
    service_port = ":{{ .Values.servicePort  | default "10715" }}"
    grpc_port = ":{{ .Values.grpcPort  | default "10705" }}"
    log_level = {{ .Values.logLevel | default "Info" | quote }}

    [mongo_config]
        Address   = {{ .Values.mongo.address | quote }}
        Username  = {{ .Values.mongo.username | default "" | quote }}
        Password    = {{ .Values.mongo.password | default "" | quote }}
        Dbname  = {{ .Values.mongo.dbname | default "DCS_BLOCK_SERVICE_DB" | quote }}

    [oss_config]
        Platform = {{ .Values.oss.platform | quote }}
        Host = {{ .Values.oss.host | quote }}
        Port = {{ .Values.oss.port | quote }}
        AccessKeyID = {{ .Values.oss.accessKeyID | quote }}
        SecretAccessKey = {{ .Values.oss.secretAccessKey | quote }}
        ApiVersion = {{ .Values.oss.apiVersion | quote }}
        Bucket = {{ .Values.oss.bucket | quote }}
        UseSSL = {{ .Values.oss.useSSL }}
