name: dcs-auth
version: 1.0.0
description: Auth service for DCS.
keywords:
- dcs
- auth
home: https://www.datamesh.com/
maintainers:
- name: Jianjun Xie
  email: jianjunxie@datamesh.com
engine: gotpl
