# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: kafka
spec:
  type: LoadBalancer
  ports:
  - port: 9092
  # [podname].broker.kafka.svc.cluster.local
  selector:
    app: kafka
