apiVersion: v1
kind: Service
metadata:
  name: {{ template "dcs-auth.fullname" . }}
  labels:
    app: {{ template "dcs-auth.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: dcs-auth-svc
    port: {{ .Values.servicePort | default "10400" }}
    targetPort: {{ .Values.servicePort | default "10400" }}
  - name: dcs-auth-grpc
    port: {{ .Values.grpcPort | default "10401" }}
    targetPort: {{ .Values.grpcPort | default "10401" }}
  clusterIP: None
  selector:
    app: {{ template "dcs-auth.fullname" . }}
