apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dcs-lic-gen.fullname" . }}
  labels:
    app: {{ template "dcs-lic-gen.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.properties: |-
    server.port= {{ .Values.servicePort | default "6500" }}
    service.name = {{ .Values.servername }}
    license.rsa.private.key = MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAISX9Vk8y8Wu+CVBdA2YYWNi8cJhhpFT0QTFXSrgBN5YW3xpoRKW/1z5bIEHyfg0bt9oN/5wps1i4oxu48hsWeLWj+sCv4kQv2CknQHZiFLvtzrw5WjlWfKegKsY8YkbtZ6uMz4tcMdWoeAPvFhrMRUmvCo05XVP4aILxzUCd1G1AgMBAAECgYB14H5PWjwyP4392QWqfHjAGZuiWn9+vYwJ+MgOMOBDJzwWC/YVh8X4SwoKX/lPPpX+6TE2c8Hmv+12ObMpYCI7vwlo5eVKZANE91KW9NiFwDuN3w0z3NFVTO86+/aRre9k+Gba51oMap5rR9UpswDBtzoYV8YnWKjrAb+h0LC/lQJBAL7KzagzqeGzbiXnZLQ8lR7sTOFLylWoEtS+1MSHCxymSa6mObFq0KvshT/cZGdIh/4OIW/x1EOpe9u2fC2zu5cCQQCx6R5Jyq5QVyud9whu6tzhnrAGj8KJyMHFvSUaKN3uCsfHuj4Fcjdgdidc84MpkzXkcIEgdMpuFTOpK7Tn7XaTAkBEJgp5hyKqFL5GWbWVz4HwTrVTUBAQsn0vco5rOFVWwWrWMFexMJciodQisGVIoxa4P3HgG4AXPwWXwEHwzR83AkBmNPiTh/7QZOPH4i1UG1U9wL57ZodqRI0dnmX8O1IT+NmA4nvTASTTI83FVpgZgFrLm95y2OWajE+bdmJ9gyxFAkAwkBdmAJMSPMb4CoefFv4XMI1aZIuxgUMN39G0/fvq8b4ZEl8z2rxhMBv6X9WlWyMoHdVIDAmgJuIoDd4yNNCb

    auth.grpc.host = {{ .Values.auth.authServiceHost }}
    auth.grpc.port = {{ .Values.auth.authGrpcPort }} 
    auth.cookie.name = {{ .Values.auth.cookieName }}
    auth.cookie.domain={{ .Values.auth.cookieDomain | default "" }}
    auth.login.path = {{ .Values.auth.loginPath | default "/login" }}
    auth.logout.path = {{ .Values.auth.logoutPath | default "/logout" }}
    auth.userinfo.path = {{ .Values.auth.userinfoPath | default "/userinfo" }}
    auth.logout.redirect.path = {{ .Values.auth.logoutRedirectPath }}
    
    license.order.server.host = {{ .Values.services.measuringliverServiceHost }}
    license.order.server.port = {{ .Values.services.measuringliverServicePort }}
    license.portal.server.host = {{ .Values.services.portalServerHost }}
    license.portal.server.port = {{ .Values.services.portalServerPort }}

    spring.datasource.url = jdbc:mysql://{{ .Values.datasource.host }}:{{ .Values.datasource.port | default "3306" }}/{{ .Values.datasource.dbname | default "HOLO_LICENSE_DB" }}?{{ .Values.datasource.tinyInt1isBit | default "true" }}&{{ .Values.datasource.autoReconnect | default "true" }}&{{ .Values.datasource.autoReconnectForPools | default "false" }}&{{ .Values.datasource.useUnicode | default "true" }}&{{ .Values.datasource.characterEncoding | default "UTF-8" }}&{{ .Values.datasource.useSSL | default "false" }}
    spring.datasource.username = {{ .Values.datasource.username }}
    spring.datasource.password = {{ .Values.datasource.password }}
    spring.datasource.driver-class-name = com.mysql.jdbc.Driver
    spring.datasource.maximum-pool-size = 50
    spring.datasource.max-wait = 60000
    spring.datasource.min-idle = 5
    spring.datasource.initial-size = 5
    spring.datasource.validation-query = SELECT 1
    spring.datasource.test-on-borrow = true
    spring.datasource.max-idle = 20
    spring.datasource.time-between-eviction-runs-millis = 60000
    spring.datasource.jdbc-interceptors = ConnectionState;SlowQueryReport(threshold=0)
    
    #show sql statement
    spring.jpa.database = {{ .Values.sql.dbType }}
    spring.jpa.show-sql = true
    spring.http.multipart.max-file-size = 4096MB
    spring.http.multipart.max-request-size = 4096MB
    spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    

