apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "library-svc.fullname" . }}
  labels:
    app: {{ template "library-svc.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  service_conf.toml: |-
    title = "DCS Library Configuration. Copyright @DataMesh, 2017."
    service_port = ":{{ .Values.servicePort  | default "10810" }}"
    log_level = {{ .Values.logLevel | default "Debug" | quote }}

    region = {{ .Values.region | quote }}
    top_domain = {{ .Values.topDomain | quote }}
    session_cookie_name = {{ .Values.sessionCookieName | quote }}
    session_cookie_domain = {{ .Values.sessionCookieDomain | default "" | quote }}

    drive_server_address = "http://{{ .Values.services.driveServiceHost }}:{{ .Values.services.driveServicePort }}"
    auth_server_address    = "{{ .Values.services.authServiceHost }}:{{ .Values.services.authServicePort }}"

    login_path = {{ .Values.auth.loginPath | default "/login" | quote }}
    logout_path = {{ .Values.auth.logoutPath | default "/logout" | quote }}
    userinfo_path = {{ .Values.auth.userinfoPath | default "/userinfo" | quote }}
    logout_redirect_path = {{ .Values.auth.logoutRedirectPath | quote }}
    service_name = {{ .Values.auth.serviceName | default "library" | quote }}

    bimface_app_key = {{ .Values.bimface.appKey | quote }}
    bimface_app_secret = {{ .Values.bimface.appSecret | quote }}
    bimface_translate_callback = {{ .Values.bimface.translateCallback | quote }}
    bimface_createvr_callback = {{ .Values.bimface.createvrCallback | quote }}
    
    [mongo_config]
        Address   = {{ .Values.mongo.address | quote }}
        Username  = {{ .Values.mongo.username | default "" | quote }}
        Password    = {{ .Values.mongo.password | default "" | quote }}
        Dbname  = {{ .Values.mongo.dbname | default "DCS_LIBRARY_DB" | quote }}
