kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-1
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0c64f231be1758804
    fsType: ext4