kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-4
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-092d9517d668dfcd3
    fsType: ext4