kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-3
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-057136c990cf74c23
    fsType: ext4