kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-2
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0af58fc7d1a93267e 
    fsType: ext4