kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-5
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0f2df539b7308f6cd
    fsType: ext4