kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc-5
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi