kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-6
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-04e8be44870c48ed7
    fsType: ext4